# docker-compose.yml
version: '3.8'

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
