server:
  port: 8080
spring:
  profiles:
    include:
      - database
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    suffix: .html
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB