server:
  port: 8081
spring:
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    suffix: .html

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:data.sql

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://${DB_IP}:3306/${DB_NAME}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true