name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-images
          path: .

      - name: Copy images to Synology NAS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USERNAME }}
          password: ${{ secrets.SYNOLOGY_PASSWORD }}
          source: "admin_image.tar,client_image.tar"
          target: "${{ secrets.DEPLOY_PATH }}"

      - name: Copy .env file to Synology NAS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USERNAME }}
          password: ${{ secrets.SYNOLOGY_PASSWORD }}
          source: ".env"
          target: "${{ secrets.DEPLOY_PATH }}"

      - name: Deploy containers on Synology NAS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USERNAME }}
          password: ${{ secrets.SYNOLOGY_PASSWORD }}
          script: |
            docker load -i ${{ secrets.DEPLOY_PATH }}/admin_image.tar
            docker load -i ${{ secrets.DEPLOY_PATH }}/client_image.tar
            cd ${{ secrets.DEPLOY_PATH }}
            docker-compose up -d
